# Cloudflare Pages configuration
name = "chooseyouraidventure"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"
